"""
Stage 5 — export ward-union sheds as ESRI shapefiles + a shareable zip.

One shapefile per (mode, scenario, band), one polygon per ward, e.g.:
  BLR_car_am_peak_15min_Sheds.shp
  BLR_bicycle_15min_Sheds.shp
DBF field names are kept <= 10 chars.

Input : data/wards/<short>_ward_sheds.geojson  (from 03)
Output: output/<SHORT>_Sheds_Shapefiles/*.shp  + <SHORT>_Sheds_Shapefiles.zip
"""

import os
import zipfile
import shutil
import geopandas as gpd

from config_loader import cfg

SHORT = cfg.CITY_SHORT.lower()
WARD_SHEDS = os.path.join(cfg.WARDS_DIR, f"{SHORT}_ward_sheds.geojson")
OUT_DIR = os.path.join(cfg.OUTPUT_DIR, f"{cfg.CITY_SHORT}_Sheds_Shapefiles")
ZIP_OUT = os.path.join(cfg.OUTPUT_DIR, f"{cfg.CITY_SHORT}_Sheds_Shapefiles.zip")

if os.path.exists(OUT_DIR):
    shutil.rmtree(OUT_DIR)
os.makedirs(OUT_DIR, exist_ok=True)

gdf = gpd.read_file(WARD_SHEDS)
print(f"Loaded {len(gdf)} ward-union sheds from {WARD_SHEDS}")

# DBF-safe field names (<=10 chars)
RENAME = {"ward_no": "Ward_No", "ward_name": "Ward_Name", "zone": "Zone",
          "mode": "Mode", "scenario": "Scenario", "band_min": "Band_Min",
          "area_km2": "Area_km2"}

written = []
for (mode, scen, band), grp in gdf.groupby(["mode", "scenario", "band_min"]):
    label = cfg.MODES[mode]["label"].lower()
    scen_part = "" if scen == "na" else f"_{scen}"
    name = f"{cfg.CITY_SHORT}_{label}{scen_part}_{int(band)}min_Sheds"
    out = grp.rename(columns=RENAME)[list(RENAME.values()) + ["geometry"]].copy()
    out_shp = os.path.join(OUT_DIR, f"{name}.shp")
    out.to_file(out_shp, driver="ESRI Shapefile")
    written.append((name, len(out)))
    print(f"  {name}.shp  ({len(out)} wards)")

# README
readme = os.path.join(OUT_DIR, "README.txt")
scen_labels = ", ".join(f"{s['key']}={s['label']}" for s in cfg.car_scenarios())
with open(readme, "w", encoding="utf-8") as f:
    f.write(
        f"{cfg.CITY_NAME} multimodal reachable-range sheds\n"
        f"{'=' * 48}\n\n"
        f"One ESRI shapefile per (mode, scenario, band); one polygon per ward\n"
        f"(union of that ward's sample-point sheds).\n\n"
        f"Modes      : Drive (car), Bike (bicycle), Walk (pedestrian)\n"
        f"Car scenarios: {scen_labels}\n"
        f"  (free_flow = TomTom traffic=false, no-congestion baseline)\n"
        f"Bands      : {', '.join(str(b) + ' min' for b in cfg.BANDS_MIN)}\n"
        f"CRS        : WGS84 / EPSG:4326\n"
        f"Source     : TomTom Routing API (calculateReachableRange)\n\n"
        f"Attribute fields:\n"
        f"  Ward_No   Ward number\n"
        f"  Ward_Name Ward / neighborhood name\n"
        f"  Zone      Assembly constituency / zone\n"
        f"  Mode      car | bicycle | pedestrian\n"
        f"  Scenario  am_peak | pm_peak | free_flow | na\n"
        f"  Band_Min  Time budget in minutes\n"
        f"  Area_km2  Reachable area (sq km)\n\n"
        f"Generated by 05_export_shed_shapefiles.py\n"
    )

if os.path.exists(ZIP_OUT):
    os.remove(ZIP_OUT)
with zipfile.ZipFile(ZIP_OUT, "w", zipfile.ZIP_DEFLATED) as zf:
    for fname in sorted(os.listdir(OUT_DIR)):
        zf.write(os.path.join(OUT_DIR, fname),
                 arcname=os.path.join(f"{cfg.CITY_SHORT}_Sheds_Shapefiles", fname))

print(f"\nWrote {len(written)} shapefiles to {OUT_DIR}")
print(f"Zip: {ZIP_OUT}  ({os.path.getsize(ZIP_OUT):,} bytes)")
